# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y

## If CONFIG_ZMK_DISPLAY is enabled, exactly zero or one
## of the following options must be set to y.
## The first option is used if none are set.
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
#CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=n

## If CONFIG_ZMK_DISPLAY is enabled, exactly zero or one
## of the following options must be set to y.
## The first option is used if none are set.
CONFIG_ZMK_DISPLAY_WORK_QUEUE_SYSTEM=y
#CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# Better conection
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Global
## Upgrade BLE power for better connection
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
## Change Corne name
CONFIG_ZMK_KEYBOARD_NAME="corne36abnt2"
## Move mouse using the keyboard
CONFIG_ZMK_POINTING=y

# Power Management Configuration
## Sleep in 30 seconds
CONFIG_ZMK_IDLE_TIMEOUT=30000
## Enable deep sleep
CONFIG_ZMK_SLEEP=y
## Deep Sleep in 30 minutes
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

## Show words per minute
CONFIG_ZMK_WIDGET_WPM_STATUS=y

## Show battery percentage
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
## Show battery reporting
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
CONFIG_ZMK_BATTERY_REPORTING=y

## Enable a widget to show the current output (USB/BLE)
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
