# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y

## If CONFIG_ZMK_DISPLAY is enabled, exactly zero or one
## of the following options must be set to y.
## The first option is used if none are set.
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
#CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=n

## If CONFIG_ZMK_DISPLAY is enabled, exactly zero or one
## of the following options must be set to y.
## The first option is used if none are set.
CONFIG_ZMK_DISPLAY_WORK_QUEUE_SYSTEM=y
#CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# Better conection
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Global
## Upgrade BLE power for better connection
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
## Change Corne name
CONFIG_ZMK_KEYBOARD_NAME="Corne36ABNT2"

## Move mouse using the keyboard
CONFIG_ZMK_POINTING=y
# Ajusta a velocidade máxima e a suavidade da aceleração do ponteiro
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
### # Enable mouse keys (for Miryoku mouse layer)
### CONFIG_ZMK_MOUSE=y

#####CONFIG_ZMK_SPLIT_ROLE_CENTRAL=1

# Power Management Configuration
## Sleep in 30 seconds
CONFIG_ZMK_IDLE_TIMEOUT=90000
## Enable deep sleep
CONFIG_ZMK_SLEEP=y
## Deep Sleep in 30 minutes
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

## Show words per minute
CONFIG_ZMK_WIDGET_WPM_STATUS=y

## Show battery percentage
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
## Show battery reporting
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
CONFIG_ZMK_BATTERY_REPORTING=y

## Enable a widget to show the current output (USB/BLE)
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y





##  ##  # Uncomment the following lines to enable the Corne RGB Underglow
##  ##  # CONFIG_ZMK_RGB_UNDERGLOW=y
##  ##  # CONFIG_WS2812_STRIP=y
##  ##  
##  ##  # Uncomment the following line to enable the Corne OLED Display
##  ##  CONFIG_ZMK_DISPLAY=y
##  ##  CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
##  ##  CONFIG_NICE_OLED_WIDGET_WPM=n
##  ##  CONFIG_NICE_OLED_WIDGET_WPM_NUMBER=n
##  ##  CONFIG_NICE_OLED_WIDGET_WPM_SPEEDOMETER=n
##  ##  CONFIG_NICE_OLED_WIDGET_WPM_GRAPH=n
##  ##  CONFIG_NICE_OLED_WIDGET_WPM_GRAPH_FIXED_RANGE=n
##  ##  CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=n
##  ##  CONFIG_NICE_OLED_WIDGET_WPM_LUNA=n
##  ##  #CONFIG_NICE_VIEW_GEM_ANIMATION=n
##  ##  CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_WPM=n
##  ##  CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=n
##  ##  CONFIG_NICE_OLED_WIDGET_STATIC_IMAGE_PERIPHERAL=n
##  ##  CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=n
##  ##  CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED=n
##  ##  CONFIG_ZMK_HID_INDICATORS=y
##  ##  CONFIG_NICE_OLED_WIDGET_RAW_HID=n
##  ##  CONFIG_NICE_OLED_WIDGET_RAW_HID_TIME=n
##  ##  # CONFIG_NICE_OLED_WIDGET_RAW_HID_TIME_CUSTOM_X=0
##  ##  # CONFIG_NICE_OLED_WIDGET_RAW_HID_TIME_CUSTOM_Y=74
##  ##  CONFIG_NICE_OLED_WIDGET_RAW_HID_VOLUME=n
##  ##  # CONFIG_NICE_OLED_WIDGET_RAW_HID_VOLUME_CUSTOM_X=0
##  ##  # CONFIG_NICE_OLED_WIDGET_RAW_HID_VOLUME_CUSTOM_Y=98
##  ##  CONFIG_NICE_OLED_WIDGET_RAW_HID_LAYOUT=n
##  ##  CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
##  ##  #CONFIG_ZMK_WIDGET_WPM_STATUS=y
##  ##  CONFIG_ZMK_POINTING=y
##  ##  CONFIG_ZMK_SLEEP=y
##  ##  CONFIG_ZMK_IDLE_TIMEOUT=30000
##  ##  CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=180000